=== shlomif/shlomi-fish-homepage/lib/article-index/article-index.dtd
<!ELEMENT index (meta,contents)>
<!ELEMENT meta EMPTY>
<!ELEMENT contents (section)+>
<!ELEMENT section (section|entry)*>
<!ELEMENT entry (p)+>
<!ELEMENT p (#PCDATA|a)*>
<!ELEMENT a (#PCDATA)>
<!ATTLIST section id ID #REQUIRED title CDATA #REQUIRED>
<!ATTLIST entry id ID #REQUIRED title CDATA #REQUIRED url CDATA #REQUIRED>
<!ATTLIST a href CDATA #REQUIRED>

=== shlomif/shlomi-fish-homepage/lib/article-index/article-index.xml
<?xml version='1.0' encoding='utf-8'?>
<?xml-stylesheet type="text/xml" href="article-index.xsl"?>
<!DOCTYPE index SYSTEM "article-index.dtd">
<index>
<meta>
</meta>
<contents>
<section id="computing" title="Essays and Articles about Computing">
<section id="software-dev-best-practices" title="Essays and Articles about Software Development Best Practices">
<entry id="what-you-should-know-about-automated-testing" title="What you should know about automated software testing" url="https://github.com/shlomif/what-you-should-know-about-automated-testing">
<p>
A brief, and mostly programming-language-agnostic, primer.
</p>
</entry>
<entry id="testing-static-sites" title="Ideas for automated tests of static web sites" url="https://github.com/shlomif/testing-static-sites">
<p>
Like those generated by static-site-generators.
</p>
</entry>
</section>
<entry id="cross_unix_portability" title="Cross UNIX Portability - Facts and Myths" url="http://discuss.fogcreek.com/joelonsoftware/default.asp?cmd=show&amp;ixPost=99574">
<p>
The title says it all pretty much.
</p>
</entry>
<entry id="version_control_systems_overview" title="The New Breed of Version Control Systems" url="https://www.shlomifish.org/philosophy/computers/software/New-Breed-of-Version-Control-Systems/">
<p>
An article giving an overview of several prominent open-source version control
systems that provide an alternative to CVS.
</p>
</entry>
<entry id="wikis_overview" title="Which Open Source Wiki Works For You?" url="http://www.oreillynet.com/pub/a/onlamp/2004/11/04/which_wiki.html">
<p>
An article giving a roundup of open-source Wiki implementations which enable
the user to create a world-editable web-site.
</p>
</entry>
<entry id="microsoft_and_drug_dealers"
title="Comparing Microsoft to Drug Dealers"
url="http://www.advogato.org/article/793.html">
<p>
An essay explaining why comparing Microsoft to drug dealers is misleading.
</p>
</entry>
<section id="perl" title="Articles and Essays about Perl">
<entry id="joy_of_perl" title="The Joy of Perl" url="http://www.nntp.perl.org/group/perl.advocacy/2108">
<p>
An essay that explains why I like Perl so much. Also see
<a href="http://perl.org.il/pipermail/perl/2004-February/004184.html">a
discussion of it in perl.org.il</a>
</p>
</entry>
<entry id="lm_solve" title="Solving Puzzles with LM-Solve" url="http://www.perl.com/pub/a/2003/11/17/lmsolve.html">
<p>
An article about the
<a href="http://www.shlomifish.org/lm-solve/">LM-Solve</a> puzzle
solving framework, and how to utilize it for a new puzzle.
</p>
</entry>
<entry id="devel_linetrace" title="Debug Your Programs with Devel::LineTrace" url="http://www.perl.com/pub/a/2005/03/31/lightning2.html?page=2">
<p>
A lightning article about how to insert debugging callbacks into a Perl
program without modifying its code.
</p>
</entry>
<entry id="nav_menus" title="Building Navigation Menus" url="http://www.perl.com/pub/a/2005/07/07/navwidgets.html">
<p>
Some general discussion of navigation menu and other site flow patterns in
web-sites and then how to utilize the
<a href="http://web-cpan.shlomifish.org/modules/HTML-Widgets-NavMenu/">HTML-Widgets-NavMenu</a>
module to generate them.
</p>
</entry>

<entry id="simulating_two_domain_website" title="Simulating a Two Domain Website on the Localhost" url="http://www.perlmonks.org/?node_id=504365">
<p>
How to test the local copy of a two-domain web-site without breaking its
links.
</p>
</entry>

<entry id="test_count" title="Using Test::Count"
    url="http://www.perl.com/pub/a/2007/04/12/lightning-four.html?page=3">
<p>
How to keep track of the number of tests executed by a Perl test script.
</p>
</entry>
<entry id="supporting-older-perl5-releases" title="About Supporting Older Releases of perl5 For CPAN Distributions" url="https://github.com/shlomif/supporting-older-perl5-releases">
<p>
Why I am unwilling to support too old versions of the perl 5 core.
</p>
</entry>
<entry id="critique_of_perl6" title="Critique of Where Perl 6 is Heading"
    url="http://freshmeat.net/articles/critique-of-where-perl-6-is-heading">
<p>
An old and out-of-date critique of where
<a href="http://perl6.org/">Perl 6</a> was heading, based on the fact that it
was such a large deviation from what Perl 5 is. I have changed my mind
after all that.
</p>
</entry>
</section>
<entry id="theming_bash" title="Theming Bash" url="http://www.onlamp.com/pub/a/onlamp/2006/02/02/bash_themes.html">
<p>
Multiple shell configurations - how to implement them and what to put inside.
</p>
</entry>
<entry id="patronage_and_self_patronage" title="Patronage and Self-Patronage" url="http://shlomif.livejournal.com/11004.html">
<p>
An essay that talks about three types of sponsorship for an open source
developer: patronage, collective patronage and self-patronage.
</p>
</entry>
<entry id="Call-for-a-fork-of-the-Linux-kernel-devs-community" title="Call for a fork of the Linux kernel developers community" url="https://github.com/shlomif/Call-for-a-fork-of-the-Linux-kernel-devs-community">
<p>
This document called for a fork of the developers’ community of the Linux
kernel, focused on friendliness and respect among the participants and
constant advocacy against disrespect and the unnecessary use of strong
language and personal insults.
</p>
</entry>
<section id="bsds" title="Essays about the BSDs">
<entry id="what-i-learned-from-porting-to-freebsd" title="What I learned from porting my projects to FreeBSD" url="https://github.com/shlomif/what-i-learned-from-porting-to-freebsd">
<p>
</p>
</entry>
<entry id="why-my-projects-cannot-support-netbsd-yet" title="Why my projects cannot support NetBSD (yet)" url="https://github.com/shlomif/why-my-projects-cannot-support-netbsd-yet">
<p>
</p>
</entry>
<entry id="why-the-BSDs-should-not-blame-USL-vs-BSDi-for-linux-dominance" title="Why the BSDs should not blame the USL vs BSDi lawsuits for Linux’s dominance" url="https://github.com/shlomif/why-the-BSDs-should-not-blame-USL-vs-BSDi-for-linux-dominance">
<p>
</p>
</entry>
</section>
<section id="games-tutorials" title="Computer games-related tutorials">
<entry id="playing-street-fighter-2-using-mame" title="Getting Street Fighter 2 Up and Running in MAME (on Linux)" url="https://github.com/shlomif/shlomif-tech-diary/blob/master/playing-street-fighter-2-using-mame.asciidoc">
<p>
</p>
</entry>
<entry id="playing-sonic-the-hedgehog-on-linux" title="Getting Sonic the Hedgehog Up and Running in Linux" url="https://github.com/shlomif/shlomif-tech-diary/blob/master/playing-sonic-the-hedgehog-on-linux.asciidoc">
<p>
</p>
</entry>
</section>
</section>
<section id="copyright_law" title="Essays about Copyright Law">
<entry id="anti_file_swapping_in_israel" title="Acting against Anti File Swapping Lawsuits in Israel" url="http://www.mail-archive.com/linux-il%40cs.huji.ac.il/msg39822.html">
<p>
An article that explains my motivation to act against anti-file-sharer lawsuits
in Israel. The link is to a Linux-IL discussion about it, but contains a link
to the original article.
</p>
</entry>
</section>
<section id="media_and_culture" title="Essays about Media and Culture">
<entry id="bazaar_style_movies" title="Bazaar-style Movies Revisited"
    url="http://advogato.org/article/789.html">
<p>
An essay about an innovative (and still theoretical) way of creating
a movie.
</p>
</entry>
</section>
</contents>
</index>
